# Generated by Django 2.1.5 on 2019-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20190309_2328'),
        ('accounts_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alowed_projects',
            field=models.ManyToManyField(blank=True, to='mainApp.Project'),
        ),
    ]
