# Generated by Django 2.1.5 on 2019-03-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0002_profile_alowed_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alowed_projects',
        ),
    ]
