# Generated by Django 2.1.5 on 2019-03-09 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('project_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Author', to=settings.AUTH_USER_MODEL)),
                ('project_developer', models.ManyToManyField(default=None, related_name='Developers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
