# Generated by Django 2.1.5 on 2019-03-09 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_developer',
            field=models.ManyToManyField(related_name='Developers', to=settings.AUTH_USER_MODEL),
        ),
    ]
