# Generated by Django 2.1.5 on 2019-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20190314_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
