# Generated by Django 2.1.5 on 2019-03-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20190315_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
