# Generated by Django 2.1.5 on 2019-03-17 15:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20190317_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
