# Generated by Django 2.1.5 on 2019-03-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='t_type',
            new_name='task_type',
        ),
    ]
