# Generated by Django 2.1.5 on 2019-03-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20190318_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='performers',
            new_name='project_performers',
        ),
    ]
