# Generated by Django 2.1.5 on 2019-03-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0003_remove_profile_alowed_projects'),
        ('mainApp', '0012_auto_20190318_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comentator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_manager.Profile')),
            ],
        ),
    ]
