# Generated by Django 2.1.5 on 2019-03-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Task'),
        ),
    ]
