# Generated by Django 2.1.5 on 2019-03-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_comment_comment_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_performers',
        ),
    ]
