# Generated by Django 2.1.5 on 2019-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20190318_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.FloatField(verbose_name='Time in hours'),
        ),
    ]
