# Generated by Django 2.1.5 on 2019-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20190318_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.FloatField(verbose_name='Estimated time in hours'),
        ),
    ]
